// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarouselBase: typeof import('./client/components/Carousel/Base.vue')['default']
    CarouselImage: typeof import('./client/components/Carousel/Image.vue')['default']
    CarouselLabel: typeof import('./client/components/Carousel/Label.vue')['default']
    CarouselRadio: typeof import('./client/components/Carousel/Radio.vue')['default']
    Layout: typeof import('./client/components/Layout.vue')['default']
    NavigationBurger: typeof import('./client/components/Navigation/Burger.vue')['default']
    NavigationContainer: typeof import('./client/components/Navigation/Container.vue')['default']
    NavigationLogo: typeof import('./client/components/Navigation/Logo.vue')['default']
    NavigationMenu: typeof import('./client/components/Navigation/Menu.vue')['default']
    Page: typeof import('./client/components/Page.vue')['default']
  }
}

export { }
